repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff
        types_or: [ python, pyi ]
      - id: ruff-format
        types_or: [ python, pyi ]
  
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.1 
    hooks:
      - id: gitleaks