# Preprocessing Pipeline
RANDOM_SEED : 42
CHUNK_MAX_LENGTH : 512
TEST_DATA_FRAC : .2
EMBEDDING_MODEL: 


# Training


# RAG System
TEMPERATURE: 0.2
TOP_P: 0.1
MODEL: meta.llama3-3-70b-instruct-v1:0
MAX_OUTPUT_TOKENS: 500
BEDROCK_CURRENT_PROMPT_ID: 